user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36'

modem:
    address: 192.168.1.1
    protocol: http
    username: useradmin
    password: nE7jA%5m
    timeout: 5
    cookies:
        UID: '{username}'
        PSW: '{password}'

internet:
    url: http://www.baidu.com
    timeout: 5

ip_detect:
    urls:
        - http://ifconfig.io/ip
        - https://ifconfig.co/ip
        - https://api.ipify.org
    timeout: 5

pppoe:
    timeout: 60

guard:
    interval: 60
